### ISSUE TITLE
Creative tab isse with servers

### ISSUE THREAD

**Issue by Nagapito** [coolsquid/SquidUtils#38]
I noticed that you fixed the issue with creative tabs on servers on May 9th but the latest version from that day (on curse site) still does not include that fix.

Until you release a new version, the current one is unplayable on servers....

**Comment by coolsquid** [comment]
Has already been fixed in my development builds. Please download the latest development builds of [SquidAPI](http://ci.rx14.co.uk/job/coolsquid/job/SquidAPI/) and [SquidUtils](http://ci.rx14.co.uk/job/coolsquid/job/SquidUtils/).

**Comment by LemADEC** [comment]
Latest development is still not working:
```
[23:51:42] [Server thread/ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: coolsquid.squidutils.handlers.CommonHandler.registerCreativeTabs()V
>
>       at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:?]
>       at cpw.mods.fml.common.Loader.initializeMods(Loader.java:718) ~[Loader.class:?]
>       at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
>       at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) ~[FMLCommonHandler.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) ~[lt.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: coolsquid.squidutils.handlers.CommonHandler.registerCreativeTabs()V
>       at coolsquid.squidutils.SquidUtils.init(SquidUtils.java:241) ~[SquidUtils.class:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
>       at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
>       at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
>       at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
>       at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
>       at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
>       at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
>       at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
>       at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
>       at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
>       at cpw.mods.fml.common.Loader.initializeMods(Loader.java:716) ~[Loader.class:?]
>       ... 5 more
```
using
SquidAPI-1.1.13.23.jar
SquidUtils-2.1.2.22.jar

**Comment by coolsquid** [comment]
That crash should simply not be possible with the latest version... o.O

I will look at it the next time I get to my computer.

**Comment by coolsquid** [comment]
I have released a new version, which contains a fix.
